//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllFacultyInSinglePlatformWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_RegistrationForm
    {
        public int Id { get; set; }
        public string Std_Name { get; set; }
        public string Std_EmailId { get; set; }
        public string Std_MobileNo { get; set; }
        public string Std_City { get; set; }
        public string Std_State { get; set; }
        public string Std_Country { get; set; }
        public string Course { get; set; }
        public Nullable<System.DateTime> Std_DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
